---
title: "Discussion"
output:
  workflowr::wflow_html:
    toc: true
    code_folding: hide
editor_options:
  chunk_output_type: console
---

## Caveats

Caveats to be aware of:

1) We are just looking at trends over time.
2) Mapping/modeling techniques of pre-settlement are different from the satellite maps of today.
3) Differentiation between open/closed canopy classes were determined in workshops led by local experts.

## Discussion

### Summary and patterns

Overall, late-successional forest in this part of Oregon has declined from pre-European conditions to present-day. Across the area, we saw an average loss of 60% of LS stands, with nearly all ecosystems losing open, and coastal ecosystems losing closed late successional. However, some areas have experienced a gain in LS forest, perhaps due to fire suppression.

### Our contributions

Our results demonstrate the importance of considering open canopy LS, especially in fire adapted ecosystems. If we only consider ‘closed-canopy’ late succession habitat, we may underestimate those areas. Consideration of both canopy types could lead to a fuller understanding of the ecosystems at hand, as well as increased forest resiliency and stronger and more inclusive management strategies moving forward.

### Future directions



## Acknowledgements

- LANDFIRE Team
- The Conservation Data Lab (https://conservationdatalab.org/)

